/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   default-theme.js
 *   default-theme.js
 */

/// <reference path="typography.d.ts" />
/// <reference path="colors.d.ts" />

