/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   index.html
 */

/// <reference path="../@webcomponents/webcomponentsjs/webcomponents-bundle.d.ts" />
/// <reference path="../@polymer/iron-component-page/iron-component-page.d.ts" />

