/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   typography.js
 *   typography.js
 */

/// <reference path="din-pro.d.ts" />

